## 1. Import NumPy as np

In [2]:
import numpy as np

## 2. Créer un tableau de 10 zéros 

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## 3. Créer un tableau de 10 uns

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## 4. Créer un tableau de 10 cinq

In [10]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
# Ne pas exécuter cette cellule

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Créer un tableau des nombres entiers de 10 à 50

In [62]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

## 6. Créer un tableau de tous les entiers pairs de 10 à 50

In [63]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

## 7. Créer une matrice 3x3 avec des valeurs allant de 0 à 8

In [18]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 8. Créer une matrice d'identité 3x3

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 9. Utiliser NumPy pour générer un nombre aléatoire entre 0 et 1

NOTE : La valeur de votre résultat devrait être différente de celle indiquée ci-dessous.

In [66]:
np.random.random()

0.4353223926182769

## 10. Utiliser NumPy pour générer un tableau de 25 nombres aléatoires tirés d'une distribution normale standard.

NOTE : Les valeurs de votre résultat devraient être différentes de celles indiquées ci-dessous.

In [27]:
np.random.randn(25)

array([-1.08158785,  1.22784191,  0.25256671, -0.00429365, -0.51672674,
        2.79074042,  0.0758678 ,  0.62432204,  0.19547871, -0.64280377,
        0.5595357 ,  1.16669974, -0.52950513,  0.5439634 , -0.05054718,
       -1.69535791,  0.28899602, -0.62345402, -0.37128454, -0.19558622,
        1.32156496, -0.39992917, -0.36692795,  1.84046108, -0.31132222])

## 11. Créer la matrice suivante

In [ ]:
# Ne pas exécuter cette cellule

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [32]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

## 12. Créer un tableau de 20 points linéairement espacés entre 0 et 1

In [34]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
# Ne pas exécuter cette cellule

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Indexation et sélection NumPy

On vous donne maintenant une matrice de départ (n'oubliez pas d'exécuter la cellule ci-dessous !), et on vous demande de reproduire les sorties de la matrice résultante 

In [35]:
# EXÉCUTER CETTE CELLULE - C'EST NOTRE MATRICE DE DÉPART
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### 13. Écrire un code qui reproduit la sortie indiquée ci-dessous

Faites attention à ne pas exécuter la cellule immédiatement au-dessus de la sortie, sinon vous ne pourrez plus voir la sortie attendue.

In [38]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# Ne pas exécuter cette cellule

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

### 14. Écrire le code qui reproduit la sortie montrée ci-dessous

In [40]:
mat[3,-1]

20

In [ ]:
# Ne pas exécuter cette cellule 

20

### 15. Écrire le code qui reproduit la sortie montrée ci-dessous

In [44]:
mat[:3,[1]]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# ne pas exécuter cette cellule

array([[ 2],
       [ 7],
       [12]])

### 16. Écrire le code qui reproduit la sortie montrée ci-dessous

In [47]:
mat[-1,:]

array([21, 22, 23, 24, 25])

In [ ]:
# Ne pas exécuter cette cellule

array([21, 22, 23, 24, 25])

### 17. Écrire le code qui reproduit la sortie montrée ci-dessous

In [50]:
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# Ne pas exécuter cette cellule

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Opérations NumPy

### 18. Obtenir la somme de toutes les valeurs de mat

In [52]:
mat.sum()

325

In [ ]:
# Ne pas exécuter cette cellule

325

### 19. Obtenir l'écart type des valeurs de mat

In [54]:
np.std(mat)

7.211102550927978

In [ ]:
# Ne pas exécuter cette cellule

7.211102550927978

### 20. Obtenir la somme de toutes les colonnes de mat

In [56]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])

In [ ]:
# Ne pas exécuter cette cellule

array([55, 60, 65, 70, 75])

## Question Bonus

Nous allons beaucoup travailler avec des données aléatoires avec NumPy, mais existe-t-il un moyen de s'assurer que nous obtenons toujours les mêmes nombres aléatoires ? [Cliquez ici pour un indice](https://www.google.com/search?q=numpy+random+seed&rlz=1C1CHBF_enUS747US747&oq=numpy+random+seed&aqs=chrome..69i57j69i60j0l4.2087j0j7&sourceid=chrome&ie=UTF-8)

In [61]:
np.random.seed(2)
np.random.random()

0.43599490214200376

**Bon courage !**